spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/userservice?serverTimezone=UTC
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    user: user
    password: user
    schemas: userservice
    url: jdbc:mysql://host.docker.internal:3308/userservice?serverTimezone=UTC
    enabled: false

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

