spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/userservice
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://host.docker.internal:5432/userservice
    user: user
    password: user

  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
logging:
  file:
    name: myapp.log
    path: /var/log/myapp
