spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/userservice
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    user: user
    password: user
    schemas: userservice
    url: jdbc:mysql://host.docker.internal:3306/userservice
    enabled: true

  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false

