CREATE TABLE IF NOT EXISTS roles
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users_roles
(
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES users (id),
    FOREIGN KEY (ROLE_ID) REFERENCES roles (id),
    PRIMARY KEY (USER_ID, ROLE_ID)
);